package com.example1.demo1.test.test.test;


import jdk.nashorn.internal.parser.JSONParser;
import org.json.JSONException;

import java.util.ArrayList;
import java.util.List;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.alibaba.fastjson.JSONArray;

public class Jmetertest1 {
    public static void main(String[] args){

        try {
            String data_obj = "{\n" +
                    "    \"code\":0,\n" +
                    "    \"data\":{\n" +
                    "        \"currentPage\":1,\n" +
                    "        \"pageSize\":2147483647,\n" +
                    "        \"rows\":[\n" +
                    "            {\n" +
                    "                \"applicationId\":411372482,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch987\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067442,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698421000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050468,\n" +
                    "                \"offerApprovalStageId\":410103506,\n" +
                    "                \"offerId\":410078510,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372483,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch989\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067443,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698421000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050469,\n" +
                    "                \"offerApprovalStageId\":410103507,\n" +
                    "                \"offerId\":410078511,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372480,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch983\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067440,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698420000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050466,\n" +
                    "                \"offerApprovalStageId\":410103504,\n" +
                    "                \"offerId\":410078508,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372481,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch985\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067441,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698420000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050467,\n" +
                    "                \"offerApprovalStageId\":410103505,\n" +
                    "                \"offerId\":410078509,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372479,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch980\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067439,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698419000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050465,\n" +
                    "                \"offerApprovalStageId\":410103503,\n" +
                    "                \"offerId\":410078507,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372477,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch976\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067437,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698418000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050463,\n" +
                    "                \"offerApprovalStageId\":410103501,\n" +
                    "                \"offerId\":410078505,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372478,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch978\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067438,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698418000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050464,\n" +
                    "                \"offerApprovalStageId\":410103502,\n" +
                    "                \"offerId\":410078506,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372474,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch970\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067434,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698417000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050460,\n" +
                    "                \"offerApprovalStageId\":410103498,\n" +
                    "                \"offerId\":410078502,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372475,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch972\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067435,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698417000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050461,\n" +
                    "                \"offerApprovalStageId\":410103499,\n" +
                    "                \"offerId\":410078503,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372476,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch974\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067436,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698417000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050462,\n" +
                    "                \"offerApprovalStageId\":410103500,\n" +
                    "                \"offerId\":410078504,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372472,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch966\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067432,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698416000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050458,\n" +
                    "                \"offerApprovalStageId\":410103496,\n" +
                    "                \"offerId\":410078500,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372473,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch968\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067433,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698416000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050459,\n" +
                    "                \"offerApprovalStageId\":410103497,\n" +
                    "                \"offerId\":410078501,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372469,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch960\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067429,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698415000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050455,\n" +
                    "                \"offerApprovalStageId\":410103493,\n" +
                    "                \"offerId\":410078497,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372470,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch962\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067430,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698415000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050456,\n" +
                    "                \"offerApprovalStageId\":410103494,\n" +
                    "                \"offerId\":410078498,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372471,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch964\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067431,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698415000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050457,\n" +
                    "                \"offerApprovalStageId\":410103495,\n" +
                    "                \"offerId\":410078499,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372467,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch956\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067427,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698414000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050453,\n" +
                    "                \"offerApprovalStageId\":410103491,\n" +
                    "                \"offerId\":410078495,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372468,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch958\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067428,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698414000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050454,\n" +
                    "                \"offerApprovalStageId\":410103492,\n" +
                    "                \"offerId\":410078496,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372465,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch952\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067425,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698413000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050451,\n" +
                    "                \"offerApprovalStageId\":410103489,\n" +
                    "                \"offerId\":410078493,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372466,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch954\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067426,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698413000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050452,\n" +
                    "                \"offerApprovalStageId\":410103490,\n" +
                    "                \"offerId\":410078494,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372463,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch949\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067423,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698412000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050449,\n" +
                    "                \"offerApprovalStageId\":410103487,\n" +
                    "                \"offerId\":410078491,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372464,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch950\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067424,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698412000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050450,\n" +
                    "                \"offerApprovalStageId\":410103488,\n" +
                    "                \"offerId\":410078492,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372460,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch944\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067420,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698411000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050446,\n" +
                    "                \"offerApprovalStageId\":410103484,\n" +
                    "                \"offerId\":410078488,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372461,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch946\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067421,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698411000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050447,\n" +
                    "                \"offerApprovalStageId\":410103485,\n" +
                    "                \"offerId\":410078489,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372462,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch948\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067422,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698411000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050448,\n" +
                    "                \"offerApprovalStageId\":410103486,\n" +
                    "                \"offerId\":410078490,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372457,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch938\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067417,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698410000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050443,\n" +
                    "                \"offerApprovalStageId\":410103481,\n" +
                    "                \"offerId\":410078485,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372458,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch940\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067418,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698410000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050444,\n" +
                    "                \"offerApprovalStageId\":410103482,\n" +
                    "                \"offerId\":410078486,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372459,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch942\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067419,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698410000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050445,\n" +
                    "                \"offerApprovalStageId\":410103483,\n" +
                    "                \"offerId\":410078487,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":411372456,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"feifei_batch936\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067416,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1617698409000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"fa351f10-f919-4108-b82a-ddb020f00d6e\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"自动化测试-飞飞\",\n" +
                    "                \"logId\":410050442,\n" +
                    "                \"offerApprovalStageId\":410103480,\n" +
                    "                \"offerId\":410078484,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":418460897,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"况仁力\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067289,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1615969667000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"3be23eaa-da50-4043-af56-7200cc48a5b3\",\n" +
                    "                \"jobManagerId\":410130771,\n" +
                    "                \"jobManagerName\":\"yangzhiyong\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"yxb职位名称\",\n" +
                    "                \"logId\":410050341,\n" +
                    "                \"offerApprovalStageId\":410102915,\n" +
                    "                \"offerId\":410078148,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":410736192,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"AC-0010\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067262,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1615541706000,\n" +
                    "                \"initiatorId\":410079170,\n" +
                    "                \"initiatorName\":\"zhangyanpeng\",\n" +
                    "                \"jobId\":\"23f19016-6ace-42c1-a71b-0075e7005991\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"dmj测试职位\",\n" +
                    "                \"logId\":410050318,\n" +
                    "                \"offerApprovalStageId\":410102884,\n" +
                    "                \"offerId\":410077889,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            },\n" +
                    "            {\n" +
                    "                \"applicationId\":418461261,\n" +
                    "                \"applicationStage\":\"沟通offer\",\n" +
                    "                \"approvalResult\":1,\n" +
                    "                \"candidateName\":\"高维腾\",\n" +
                    "                \"departmentId\":410004109,\n" +
                    "                \"flowId\":410067245,\n" +
                    "                \"hired\":false,\n" +
                    "                \"initiatedAt\":1615462799000,\n" +
                    "                \"initiatorId\":410058712,\n" +
                    "                \"initiatorName\":\"yangzhiyong\",\n" +
                    "                \"jobId\":\"3be23eaa-da50-4043-af56-7200cc48a5b3\",\n" +
                    "                \"jobManagerId\":410130771,\n" +
                    "                \"jobManagerName\":\"yangzhiyong\",\n" +
                    "                \"jobRankName\":\"\",\n" +
                    "                \"jobTitle\":\"yxb职位名称\",\n" +
                    "                \"logId\":410050301,\n" +
                    "                \"offerApprovalStageId\":410102856,\n" +
                    "                \"offerId\":410078089,\n" +
                    "                \"rejected\":false,\n" +
                    "                \"version\":\"1.0\"\n" +
                    "            }\n" +
                    "        ],\n" +
                    "        \"total\":31,\n" +
                    "        \"totalPage\":1\n" +
                    "    },\n" +
                    "    \"msg\":\"成功\",\n" +
                    "    \"success\":true\n" +
                    "}" ;

//            JSONObject data_obj_rows = data_obj.getJSONObject("data");
            JSONObject data_obj_rows = JSONObject.parseObject(data_obj);
            JSONArray data_array = data_obj_rows.getJSONArray("rows");   //data为数组

            int len = data_array.size();                                                //获取data数组的长度
            String strlen = Integer.toString(len);
            List list1 = new ArrayList();

            for(int i=0;i<len;i++) {
                Object data_arrayOfferId=data_array.getJSONObject(i).get("offerId");
                String name = "offerId";
            }

        }catch (Throwable ex) {
            throw ex;
        }
    }


}
